/**
 * Portable identities are UUIDv4 strings generated by SQLite for persisted
 * rows. Draft attachments need their identity before the first save so inline
 * references can point at them, and the database trigger accepts any valid
 * UUIDv4, so drafts carry one generated here.
 */
export const createDraftPortableId = (): string =>
  'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (char) => {
    const random = Math.floor(Math.random() * 16);
    const value = char === 'x' ? random : (random % 4) + 8;
    return value.toString(16);
  });
